### ISSUE TITLE
2 times on the same page

### ISSUE THREAD

**Issue by fabien-corail** [kimyvgy/simple-scrollspy#14]
Hi, 

Is it possible to use the function 2 times (cf. 2 different places/list) on the same page ?

**Comment by robhuska** [comment]
I have an idea for this, but the code will need some updating. There needs to be an ability to define your own scrolling container. I will put in a feature enhancement request for this. I have modified the code myself to allow for this, but it is janky and should/could be done better.

**Comment by kimyvgy** [comment]
I will close this issue, new feature is added by this #15
