### ISSUE TITLE
Feature Request: User Defined Scrolling Container

### ISSUE THREAD

**Issue by robhuska** [kimyvgy/simple-scrollspy#15]
Allow the user to target other containers that scroll other than the `body`. I have pulled the master and made some modifications myself, but they are pretty janky and could be done cleaner by the main developer.

**Comment by robhuska** [comment]
I have created a pull request with my version of the implementation. #17

**Comment by kimyvgy** [comment]
@robhuska Nice work! I will re-check and release soon!

**Comment by kimyvgy** [comment]
@robhuska this feature has been released as v2.1.0. Thank you for your PR.
