### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by wilr** [kimyvgy/simple-scrollspy#20]
Looks like a file may be missing.

kimyvgy.github.io/:49 GET https://kimyvgy.github.io/simple-scrollspy/demo/dist/simple-scrollspy.min.js net::ERR_ABORTED 404

(index):52 Uncaught ReferenceError: scrollSpy is not defined
    at window.onload ((index):52)

**Comment by kimyvgy** [comment]
Thank you for your feedback. It will be fixed tonight.

**Comment by fabien-corail** [comment]
It's still not working

**Comment by papakai** [comment]
`simple-scrollspy.min.js:1 Failed to load resource: the server responded with a status of 404 ()
(index):52 Uncaught ReferenceError: scrollSpy is not defined
    at window.onload ((index):52)`

**Comment by kimnh-0823** [comment]
The commit e22f1d1 fixed this issue.

**Comment by kimyvgy** [comment]
The commit e22f1d1 fixed this issue. The demo page is working now.
