### ISSUE TITLE
New option offset for section

### ISSUE THREAD

**Issue by projct1** [kimyvgy/simple-scrollspy#28]
I have sticky horizontal panel https://skr.sh/sAbFQJdT4g4, but she overlaps my header section https://skr.sh/sAbTtGZONrn.
So, need new option `offset` equals height of this panel.

**Comment by kimyvgy** [comment]
@projct1 Could you please give me the link to Codepen (something like that) or explain to me how to reproduce this issue?

**Comment by projct1** [comment]
@kimyvgy https://codepen.io/projct1/pen/eYEeQvY

**Comment by kimyvgy** [comment]
@projct1 I see. In this case, a simple way is only to increase the `offset` value. May you try it?

**Comment by projct1** [comment]
@kimyvgy The `offset` parameter is not for this case. It is for activating the navigation class, not for displacement when scrolling. In my case, when i click to navigation link, i need to scroll to section position minus height of my height navigation.

**Comment by kimyvgy** [comment]
@projct1 Oh, I got it. If you want the offset when you click to navigation link, you can try the `smoothScroll` feature.

```javascript
import jumpTo from 'jump.js'

scrollSpy('#main-menu', {
  // ....,

  // enable smooth scroll:
  // - true: enable with the default scroll behavior
  // - false: disable this feature
  // - object: enable with some options that will pass to `Element.scrollIntoView` or `smoothScrollBehavior`
  //   + Default behavior: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
  //   + Jump.js: https://www.npmjs.com/package/jump.js
  smoothScroll: {
    duration: 1000, // only works with jump.js,
    offset: -100,   // only works with jump.js,
  },

  // customize scroll behavior,
  // - default: Element.scrollIntoView({ ...smoothScroll, behavior: 'smooth' })
  // - customize: you can define your scroll behavior. Ex: use `jump.js`, jQuery, .etc
  smoothScrollBehavior: function(element, options) {
    // use `jump.js` instead of the default scroll behavior
    jumpTo(element, options)
  }
})
```

**Comment by projct1** [comment]
@kimyvgy Ok, big thanks :D
