### ISSUE TITLE
Implement Github Actions

### ISSUE THREAD

**Issue by kimyvgy** [kimyvgy/simple-scrollspy#31]
Please implement Github Actions to auto-publish this package to NPM when having new tag.

**Comment by DonBarbaro** [comment]
Hi I would like to work on this, can u give more info and assign it to me?

**Comment by kimyvgy** [comment]
@DonBarbaro Of course I am.

**Comment by kimyvgy** [comment]
Please create `.github/workflows/npm-publish.yml` file. I want to use Github Actions to automatic build & release package to NPM.

For example:
- I push a new version to master branch with tagged as `v2.0.4`
- Github triggers a job to publish new version with some commands needed to do: `npm run build` > `npm run release` > `npm publish`
- After that, new version 2.0.4 will available in NPM

**Comment by kimyvgy** [comment]
@DonBarbaro You are working on this issue, aren't you?

**Comment by DonBarbaro** [comment]
no I am not able to do that, right now I am working on different project, sorry @kimyvgy

**Comment by kimyvgy** [comment]
Done by commit b89f282
