### ISSUE TITLE
Minimized Static file in release

### ISSUE THREAD

**Issue by trymeouteh** [kimyvgy/simple-scrollspy#34]
Please compile the package into a minimized static file for the release, for those who do not want to use ES6 import.

**Comment by kimyvgy** [comment]
@trymeouteh Thank you for your feedback.

- The minimized static file is attached on each release with filename `simple-scrollspy.min.js`.
![image](https://user-images.githubusercontent.com/13513658/218415931-9355740b-fa4c-442d-929a-a5e2ceddb672.png)

- I'm also submitting this file to `cdnjs` [PR #1463](https://github.com/cdnjs/packages/pull/1463). After merged, we can load `simple-scrollspy.min.js` file from CDN instead.

**Comment by kimyvgy** [comment]
Since v2.x, the `simple-scrollspy.min.js` is available on `demo/dist` folder.
