### ISSUE TITLE
Refactor: Add throttle for the scroll event handler

### ISSUE THREAD

**Issue by kimyvgy** [kimyvgy/simple-scrollspy#41]
When scrolling fast, the scroll event handler is called too many times. Therefore, the `activeClass` adds / removes to every the menu items.

Expect: Only add `activeClass` 1 time for the menu item when scrolling stopped.

**Comment by peekxc** [comment]
Can confirm this seems to only work if you scroll very slowly...

**Comment by kimyvgy** [comment]
This issue has been resolved and closed, as it has not occurred since version 2.5.0. The `activeClass` is now added only once, as expected.
