### ISSUE TITLE
Navbar enhancement

### ISSUE THREAD

**Issue by akshaykaluse35** [kimyvgy/simple-scrollspy#46]
![image](https://github.com/kimyvgy/simple-scrollspy/assets/69835893/3039d0f4-89cd-47a4-8468-b989003749da)
We can make navbar more interesting and eye catching

**Comment by akshaykaluse35** [comment]
Please assign me this issue with hacktober fest label, so I can start working on it..

**Comment by kimyvgy** [comment]
Ok. Please go ahead!

**Comment by akshaykaluse35** [comment]
@kimyvgy can you assign it with hacktoberfest label, It'll help me a lot. Thank you :)

**Comment by kimyvgy** [comment]
@akshaykaluse35 Hacktoberfest is using hacktoberfest topic of repository level now. Please feel free to create your PR!
