### ISSUE TITLE
refactor: adding a smooth scroll

### ISSUE THREAD

**Issue by noisybird** [kimyvgy/simple-scrollspy#9]
Hey man, it's a great script, and it seems to work very well. I would suggest adding a smooth scroll though, because it really gives the viewer a sense of what is going on instead of just checking the browser scrollbar.

**Comment by kimyvgy** [comment]
@noisybird That's a great idea. Thank you for your suggestion. It will be added soon. If you have free time, you also can make PR for that. :)

**Comment by noisybird** [comment]
Thanks, sorry, newbie question, what is "PR"?

**Comment by roshad** [comment]
> Thanks, sorry, newbie question, what is "PR"?

pull request

**Comment by austriker27** [comment]
Btw smoothscroll is pretty easy to add in vanilla HTML, check out this article: https://css-tricks.com/snippets/jquery/smooth-scrolling/. It might help you, although I dont know about your specific implementation.
